---
- hosts: ansiblehosts
  - name: add a group
    group:
      name: developers
      state: present

  - name: Create a login user
    user:
      name: {{ uusername }}
      password: {{ upassword | password_hash('sha-512')}}
      groups: developers, root
      append: yes
      state: present
      shell: /bin/bash
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
  when: assigned_role == "yes"    
