---

  - name: Install epel release
    yum:
      name: epel-release
      state: latest

  - name: Docker Repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      mode: 0700
      force_basic_auth: yes

  - name: Update repository
    yum: name=* 
         state=latest

  - name: Install development tools
    yum:
      name: "@Development tools"
      state: present

  - name: Remove docker old version
    yum:
      name: "{{ item }}"
      state: absent 
    with_items:
       - docker
       - docker-common 
       - container-selinux
       - docker-selinux
       - docker-engine 
       - docker-engine-selinux

  - name: Install docker
    yum:
      name: docker-ce
      state: latest

  - name: Install python-pip
    yum:
      name: python-pip
      state: latest

  - name: Upgrade pip
    pip:
      name: pip
      extra_args: --upgrade
